--- 
document:
  name: "Linee guida open data comune Palermo"
  description: "Questo documento regola le attività di pubblicazione degli open data al comune Palermo"    
  tags:
    - "open data"
    - "amazing project"
