--- 
document:
  name: "Linee guida open data Comune di Palermo"
  description: "Questo documento regola le attività di pubblicazione degli open data al comune Palermo"    
  tags:
    - "open data"
    - "trasparenza"
    - "dati in formato aperto"
